# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos7885.dtb
dtbo-y += exynos7904-a30_jpn_kdi_00.dtbo
dtbo-y += exynos7904-a30_jpn_kdi_01.dtbo
dtbo-y += exynos7904-a30_jpn_kdi_02.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
